# File: .github/workflows/OIDC_workflow.yml

name: Run Azure Login with OIDC
on: [push]

permissions:
      id-token: write
      contents: read
jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.2e7a9f0b-900b-447f-9670-0f64bd1cd32d }}
          tenant-id: ${{ secrets.27df70d6-2bb2-46c7-8476-b65c8529190f }}
          subscription-id: ${{ secrets.f8300d33-bc97-4816-97a2-da95aa4c6271 }}
  
      - name: 'Run az commands'
        run: |
          az account show
          az group list
          pwd OIDC_workflow.yml
